---
language: bash

dist: trusty

env:
  - VERSION=1.0.1
  - VERSION=1.1.1
  - VERSION=1.2.1
  - VERSION=5.0.0-alpha1

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="willfarrell/filebeat:$VERSION"

script:
  - docker build --pull -t "$image" .
  - ~/official-images/test/run.sh -c ~/official-images/test/config.sh "$image"